index:
    path: /
    controller: App\Controller\HomeController::index
    defaults:
      template: 'home.html.twig'

addToBasket:
    path: /addToBasket
    controller: App\Controller\BasketController::add

removeFromBasket:
    path: /removeFromBasket
    controller: App\Controller\BasketController::remove
